### ISSUE TITLE
Async `copy_in` hangs

### ISSUE THREAD

**Issue by emk** [sfackler/rust-postgres#447] opened 2019-06-22 13:52 UTC
(I'm still working actively on understanding this problem, but I wanted to file a bug upstream.)

Thank you for a great library and for all your recent work on making it async!

Using the [`dbcrossbar`](https://github.com/faradayio/dbcrossbar) `master` branch and `tokio-postgres` 0.4.0-rc.2 / `tokio-postgres-native-tls` v0.1-rc.1, we're seeing easy-to-reproduce hangs in `copy_in` when working with large data sets. I can provide sample data sets and instructions if we need those to debug.

In particular, the `CopyIn` state machine [sets `state.pending_message`](https://github.com/sfackler/rust-postgres/blob/3b31551f733ad73e4357e238dc2cdb8316de9f9e/tokio-postgres/src/proto/copy_in.rs#L172-L177): 

```rust
            match state.sender.start_send(message) {
                Ok(AsyncSink::Ready) => {}
                Ok(AsyncSink::NotReady(message)) => {
                    state.pending_message = Some(message);
                    return Ok(Async::NotReady);
                }
```

...but we never re-enter the poll function here again:

```
    fn poll_write_copy_data<'a>(
        state: &'a mut RentToOwn<'a, WriteCopyData<S>>,
    ) -> Poll<AfterWriteCopyData, Error> {
```

I've tried adding logging, adjusting channel buffer sizes, forcing `notify` every time through the loop etc., but so far nothing helps. This _might_ be some kind of read/write deadlock, but I'm grasping at straws.

I hope to follow this up with more details as I figure them out.

Thank you very much for any leads you can provide. I'm happy to add instrumentation, try experiments, etc.

**Comment by sfackler** [comment] 2019-06-22 14:23
Hmm, that sounds bad!

A standalone reproduction test case would definitely be helpful. Could you also turn on trace-level logging on `tokio_postgres::proto::connection` and attach those from when you hit a deadlock?

**Comment by sfackler** [comment] 2019-06-23 04:24
Are you sure it's actually hanging, and not just really slow? I realized we aren't buffering copy_in messages which imposed a ton of overhead if the bits coming in from the Stream you give to copy_in are small. #448 should help with that.

**Comment by emk** [comment] 2019-06-24 10:50
Thank you for looking into this!

I'm sending data in ~64K chunks, with tons of extra logging turned on.

When it hangs, there's sometimes one or two brief pauses/stutters in the log output, and then everything locks up and I won't see another log line for 12+ hours. So I'm guessing it's pretty thoroughly hung.

(Also, using the stable, synchronous release of `rust-postgres`, we can `copy_in` terrabytes of data with no problem. So this appears to be a regression in the new async code.)

I'm going to retry with your patch and see how that affects things, then post some redacted logs and my aggressive logging patch. After that, I can start working on a simplified test case. (All the failing code is open source, but it's running parallel connections, so a simple case might be easier to debug.)

**Comment by sfackler** [comment] 2019-06-24 14:43
Ah yeah, if your chunk size is 64k, #448 probably isn't going to do anything.

**Comment by emk** [comment] 2019-06-25 20:05
I made a branch https://github.com/faradayio/rust-postgres/tree/extra-logging, with lots of extra logging to try to help figure this out.

Here's the relevant section of the logs, with extra logging statements taken from 

```txt
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - ENTER
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - LOOP
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - BUFFER LOOP
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - received data
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - sent
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - LOOP
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll ENTER
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - BUFFER LOOP
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_message ENTER
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_read ENTER
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_read LOOP
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_response ENTER
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_read: waiting on response
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_write ENTER
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_write LOOP
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_request ENTER
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] retrying pending request
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_write: waiting on socket 2
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_shutdown ENTER
[2019-06-25T15:50:35Z TRACE tokio_postgres::proto::connection] poll_shutdown: not ready, not closing Active
```

That means we pass through the `NotReady` branch here in `poll_write`:

```rust
                    match self.stream.start_send(message).map_err(Error::io)? {
                        AsyncSink::Ready => {
                            self.pending_request = Some(RequestMessages::CopyIn {
                                receiver,
                                pending_message: None,
                            });
                        }
                        AsyncSink::NotReady(message) => {
                            trace!("poll_write: waiting on socket 2");
                            self.pending_request = Some(RequestMessages::CopyIn {
                                receiver,
                                pending_message: Some(message),
                            });
                            return Ok(false);
                        }
                    };
```

...and we don't actually shut down because we're in `State::Active`. I'm not sure what's going on here.

Thank you for any thoughts you can provide!

**Comment by sfackler** [comment] 2019-06-25 20:25
It makes sense that we wouldn't be shutting down - that should only happen when there is no pending request and the Client's gone away.

Very weird that the last event is a NotReady from the underlying stream, since that should be triggering a wakeup when the socket is ready to write again.

The trace logging in tokio_codec would probably be useful here as well: https://docs.rs/tokio-io/0.1.8/src/tokio_io/_tokio_codec/framed_write.rs.html#183

If you can, running within `strace` would also help a bit - just be careful when posting the logs since they'll contain the raw data.

**Comment by emk** [comment] 2019-06-28 15:05
Here's some manually-redacted `strace` logging (but without `tokio_codec` unfortunately):

```
[pid 23385] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 88[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - LOOP
) = 88
[pid 23385] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 95[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - BUFFER LOOP
) = 95
[pid 23385] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 97[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - received data
) = 97
[pid 23385] write(26, "\1", 1)          = 1
[pid 22789] <... epoll_wait resumed> [{EPOLLIN, {u32=4294967295, u64=18446744073709551615}}], 1024, -1) = 1
[pid 23385] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 88[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - sent
 <unfinished ...>
[pid 22789] read(25,  <unfinished ...>
[pid 23385] <... write resumed> )       = 88
[pid 22789] <... read resumed> "\1", 128) = 1
[pid 23385] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 88[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - LOOP
 <unfinished ...>
[pid 22789] read(25,  <unfinished ...>
[pid 23385] <... write resumed> )       = 88
[pid 22789] <... read resumed> 0x7efe66c87468, 128) = -1 EAGAIN (Resource temporarily unavailable)
[pid 23385] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 95[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::copy_in] poll_write_copy_data - BUFFER LOOP
) = 95
[pid 22789] futex(0x56357379de40, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 23385] futex(0x56357379de40, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 22789] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 23385] <... futex resumed> )       = 0
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 74[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll ENTER
) = 74
[pid 23385] epoll_wait(3,  <unfinished ...>
[pid 22789] futex(0x56357379de40, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 23385] <... epoll_wait resumed> [], 1024, 0) = 0
[pid 22789] <... futex resumed> )       = 0
[pid 23385] sched_yield()               = 0
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 82[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_message ENTER
 <unfinished ...>
[pid 23385] sched_yield( <unfinished ...>
[pid 22789] <... write resumed> )       = 82
[pid 23385] <... sched_yield resumed> ) = 0
[pid 23385] sched_yield()               = 0
[pid 23385] epoll_wait(3,  <unfinished ...>
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 79[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_read ENTER
 <unfinished ...>
[pid 23385] <... epoll_wait resumed> [], 1024, 0) = 0
[pid 22789] <... write resumed> )       = 79
[pid 23385] epoll_wait(3,  <unfinished ...>
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 78[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_read LOOP
) = 78
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 83[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_response ENTER
) = 83
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 94[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_read: waiting on response
) = 94
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 80[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_write ENTER
) = 80
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 79[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_write LOOP
) = 79
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 82[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_request ENTER
) = 82
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 88[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] retrying pending request
) = 88
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 78[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::codec] sending 65524 bytes
) = 78
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 79[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_write LOOP
) = 79
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 82[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_request ENTER
) = 82
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 88[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] retrying pending request
) = 88
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 101[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_write: waiting on copy_in stream
) = 101
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 80[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_flush ENTER
) = 80
[pid 22789] sendto(37, "REDACTED"..., 16413, MSG_NOSIGNAL, NULL, 0) = 16413
[pid 22789] sendto(37, "REDACTED"..., 16413, MSG_NOSIGNAL, NULL, 0) = 16413
[pid 22789] sendto(37, "REDACTED"..., 16413, MSG_NOSIGNAL, NULL, 0) = 16413
[pid 22789] sendto(37, "REDACTED"..., 16401, MSG_NOSIGNAL, NULL, 0) = 16401
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 83[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_flush: flushed
) = 83
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 83[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_shutdown ENTER
) = 83
[pid 22789] write(2, "[2019-06-27T14:27:51Z TRACE toki"..., 108[2019-06-27T14:27:51Z TRACE tokio_postgres::proto::connection] poll_shutdown: not ready, not closing Active
) = 108
[pid 22789] write(8, "\1", 1 <unfinished ...>
[pid 23385] <... epoll_wait resumed> [{EPOLLIN, {u32=4294967295, u64=18446744073709551615}}], 1024, -1) = 1
[pid 23385] read(7,  <unfinished ...>
[pid 22789] <... write resumed> )       = 1
[pid 23385] <... read resumed> "\1", 128) = 1
[pid 22789] epoll_wait(24,  <unfinished ...>
[pid 23385] read(7,  <unfinished ...>
[pid 22789] <... epoll_wait resumed> [], 1024, 0) = 0
[pid 23385] <... read resumed> 0x7efe65462468, 128) = -1 EAGAIN (Resource temporarily unavailable)
[pid 22789] sched_yield()               = 0
[pid 23385] sched_yield( <unfinished ...>
[pid 22789] sched_yield( <unfinished ...>
[pid 23385] <... sched_yield resumed> ) = 0
[pid 22789] <... sched_yield resumed> ) = 0
[pid 23385] sched_yield( <unfinished ...>
[pid 22789] sched_yield( <unfinished ...>
[pid 23385] <... sched_yield resumed> ) = 0
[pid 22789] <... sched_yield resumed> ) = 0
[pid 23385] sched_yield()               = 0
[pid 22789] epoll_wait(24,  <unfinished ...>
[pid 23385] epoll_wait(3,  <unfinished ...>
[pid 22789] <... epoll_wait resumed> [], 1024, 0) = 0
[pid 23385] <... epoll_wait resumed> [], 1024, 0) = 0
[pid 22789] epoll_wait(24,  <unfinished ...>
[pid 23385] epoll_wait(3,  <unfinished ...>
[pid 24921] futex(0x56357379e2d8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 22788] <... futex resumed> )       = 0
[pid 22788] futex(0x56357379e0c0, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 22788] write(1, "      mode: input\n", 18      mode: input
) = 18
[pid 22788] write(1, "       Jun 27 10:27:51.341 TRCE "..., 57       Jun 27 10:27:51.341 TRCE read returned 8192 bytes
) = 57
[pid 22788] futex(0x56357379e2dc, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 24921] futex(0x7efe4c014348, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 22806] <... futex resumed> )       = 0
[pid 24921] futex(0x56357379e2dc, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 22806] futex(0x7efe4c0142f0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 24921] <... futex resumed> )       = 1
[pid 22806] <... futex resumed> )       = 0
[pid 22788] <... futex resumed> )       = 0
[pid 22788] futex(0x56357379e0c0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 22806] read(36,  <unfinished ...>
[pid 22788] <... futex resumed> )       = 0
[pid 22806] <... read resumed> "REDADCTED CSV DATA"..., 65536) = 65536
[pid 24935] <... write resumed> )       = 4096
[pid 24935] write(1, "REDADCTED CSV DATA"..., 4096 <unfinished ...>
[pid 22806] futex(0x7efe4c01434c, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 24935] <... write resumed> )       = 4096
[pid 22788] write(1, "       Jun 27 10:27:51.344 TRCE "..., 61       Jun 27 10:27:51.344 TRCE read 65536 bytes from stream
) = 61
[pid 24935] read(7, "\27\3\3@\21", 5)   = 5
[pid 22788] write(1, "       Jun 27 10:27:51.344 TRCE "..., 57       Jun 27 10:27:51.344 TRCE read returned 8192 bytes
 <unfinished ...>
[pid 24935] read(7,  <unfinished ...>
[pid 22788] <... write resumed> )       = 57
[pid 24935] <... read resumed> "REDACTED"..., 16401) = 16401
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096 <unfinished ...>
[pid 22788] write(1, "  from_locator: gs://faraday-int"..., 63  from_locator: gs://faraday-interchange/households_final_v57/
 <unfinished ...>
[pid 24935] <... write resumed> )       = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096 <unfinished ...>
[pid 22788] <... write resumed> )       = 63
[pid 24935] <... write resumed> )       = 4096
[pid 22788] write(1, "   stream: 000000000004\n", 24   stream: 000000000004
 <unfinished ...>
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096 <unfinished ...>
[pid 22788] <... write resumed> )       = 24
[pid 24935] <... write resumed> )       = 4096
[pid 22788] write(1, "    url: gs://faraday-interchang"..., 72    url: gs://faraday-interchange/households_final_v57/000000000004.csv
 <unfinished ...>
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096 <unfinished ...>
[pid 22788] <... write resumed> )       = 72
[pid 24935] <... write resumed> )       = 4096
[pid 24935] read(7,  <unfinished ...>
[pid 22788] write(1, "     Jun 27 10:27:51.345 TRCE se"..., 60     Jun 27 10:27:51.345 TRCE sending 65536 bytes to stream
 <unfinished ...>
[pid 24935] <... read resumed> "REDACTED", 5) = 5
[pid 22788] <... write resumed> )       = 60
[pid 24935] read(7,  <unfinished ...>
[pid 22788] futex(0x56357379e2d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 24935] <... read resumed> "REDACTED"..., 16401) = 16401
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] read(7, "REDACTED", 5)   = 5
[pid 24935] read(7, "REDACTED"..., 16401) = 16401
[pid 24935] write(1, "REDACTED"..., 4096) = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] read(7, "REDACTED", 5)   = 5
[pid 24935] read(7, "REDACTED"..., 16401) = 16401
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096) = 4096
[pid 24935] write(1, "REDACTED CSV DATA"..., 4096 <unfinished ...>
[pid 24921] futex(0x56357379e2d8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 22788] <... futex resumed> )       = 0
[pid 22788] futex(0x56357379e0c0, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 22788] write(1, "  to_locator: postgres://citus:X"..., 114  to_locator: postgres://citus:XXXXXX@citus.example.com:5432/citus#example_table
) = 114
[pid 22788] write(1, "   table: households_test\n", 26   table: households_test
) = 26
[pid 22788] write(1, "    stream: 000000000004\n", 25    stream: 000000000004
) = 25
[pid 22788] write(1, "     transform: copy_csv_to_pg_b"..., 38     transform: copy_csv_to_pg_binary
) = 38
[pid 22788] write(1, "      mode: input\n", 18      mode: input
) = 18
[pid 22788] write(1, "       Jun 27 10:27:51.347 TRCE "..., 57       Jun 27 10:27:51.347 TRCE read returned 8192 bytes
) = 57
[pid 22788] futex(0x56357379e2dc, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 24921] futex(0x56357379e2dc, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 22788] <... futex resumed> )       = 0
[pid 22788] futex(0x56357379e0c0, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 22788] write(1, "       Jun 27 10:27:51.349 TRCE "..., 57       Jun 27 10:27:51.349 TRCE read returned 8192 bytes
) = 57
[pid 22788] futex(0x56357379e2d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 24921] futex(0x56357379e2d8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 22788] <... futex resumed> )       = 0
[pid 22788] futex(0x56357379e0c0, FUTEX_WAKE_PRIVATE, 1
```
If we need more, I'm going to try to set up a public data set and an easy-to-reproduce build.

**Comment by emk** [comment] 2019-06-28 18:51
When I try to figure out the PIDs, there are really too many threads in that log. What I think we need is a standalone binary that generates CSV data in-process, and passes it to a target database using `copy_in`. Just an absolute bare minimum example.

**Comment by sfackler** [comment] 2019-06-29 16:54
Yeah, that'd definitely be helpful.

**Comment by sfackler** [comment] 2019-06-29 16:55
In those logs it looks like the last event was waiting on the copy_in stream rather than the database.

**Comment by emk** [comment] 2019-07-01 20:40
We are currently running a simplified test program, waiting to see if it will fail sooner or later.

**Comment by emk** [comment] 2019-07-01 22:39
We copied in 158 GB of raw CSV data before giving up, which has _usually_ been enough to trigger this bug. We'll try again tomorrow, and let you know one way or another.

**Comment by sfackler** [comment] 2019-11-30 21:09
The copy in flow has been completely rewritten with the move to async/await, so I'm going to close this.

**Closed by sfackler** 2019-11-30 21:09 UTC

**Comment by emk** [comment] 2020-01-26 13:33
I can confirm that we haven't seen this behavior in a long time. I strongly suspect (99%) it was caused by an executor deadlock in other code.

Thank you for your suggestions and for a great library!
